  mindmap
  root((Apprenant))
    Ce qu’il dit
      Dire["J’ai du mal à suivre les changements de planning."]
    Ce qu'il fait
      Fait["Consulte le planning affiché en classe."]
    Ce qu'il a besoin
      Besoin["Un accès rapide et en temps réel au planning des sessions."]
      Besoin["Des notifications ou rappels pour les sessions importantes."]

