@startuml
left to right direction

actor "Responsable de formation" as RF
actor Formateur

rectangle "Sprint 1 - Planification de formation" {
    usecase "Consulter les statistiques" as UC1
    usecase "Statistiques par module" as UC2
    usecase "Statistiques par formateur" as UC3
    usecase "Statistiques par Brief projet" as UC4
    usecase "Statistiques des competences" as UC5
    usecase "Statistiques des seances" as UC6


    UC1 <.. UC2 : <<extend>>
    UC1 <.. UC3 : <<extend>>
    UC1 <.. UC4 : <<extend>>
    UC1 <.. UC5 : <<extend>>
    UC1 <.. UC6 : <<extend>>
}

RF -- UC1
Formateur -- UC1


@enduml
