@startuml
left to right direction

actor "Responsable de formation" as Admin
actor "Formateur" as Formateur

rectangle "Planification de formation" {

    usecase "CRUD planning" as UC1
    usecase "Envoyer notifications automatiques" as UC3
    usecase "Afficher le planning en ligne" as UC4
    usecase "CRUD brifes" as UC5
    usecase "Consulter les statistiques" as  UC6

}

    Admin -- UC1
    Admin -- UC3
    Admin -- UC6

    Formateur -- UC1
    Formateur -- UC4
    Formateur -- UC5


@enduml